name: multymccarthys
description: A new Flutter project.


version: 1.0.0+1

environment:
  sdk: ">=2.2.3 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.2
  image_picker: ^0.6.0+3
  cloud_firestore: ^0.12.5+1
  firebase_auth: ^0.11.1+6
  font_awesome_flutter: ^8.4.0
  firebase_storage: ^3.0.1
  date_format: ^1.0.6
  intl: ^0.15.8
  modal_progress_hud: ^0.1.3
  intro_slider: ^2.1.1
  path_provider: ^1.1.0
  google_maps_flutter: ^2.0.2
  webview_flutter: ^2.0.12
  percent_indicator: ^2.1.3
  flutter_polyline_points: ^0.2.6
  dio: ^4.0.0
  math_expressions: ^2.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter



flutter:


  uses-material-design: true

  assets:
        - assets/images/
